In [13]:
# !pip install keras
# Remove '#' in above line if not installed keras
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset = load_iris()

# How data looks like?
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
# Step 1 : Know the Data
print(type(dataset))
print(len(dataset))

# Dataset is in Bunch Format. Bunch is a dictionary Like Object
print(dataset.keys())

# We Try ti Find Out What Values are Stored in These Attributes
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])

# Next What Define Our X and Y; Y is the Dependent on X
x = dataset['data']
print(len(x))   # To check length of dataset
y = dataset['target']
print(len(y))   # To check length of targets
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [3]:
# Step 2 : Convert Y into One Hot Encoded Vector
# One SHot Encoding is Used Because Y has Labels (0, 1, 2)- which is a Categorical Data with no Ordinal Relationship
from keras.utils import to_categorical
Ny = len(np.unique(y))
print(Ny)
Y = to_categorical(y, num_classes = Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [5]:
# Step 3 : Now We Split the Data into Two Parts - One for Training Another for Testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, Y, test_size = 0.10, shuffle = True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[6.3 3.3 4.7 1.6]
 [5.2 3.5 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.8 3.  5.5 2.1]
 [6.4 2.7 5.3 1.9]]
[[5.5 2.3 4.  1.3]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.7 1. ]
 [5.  3.4 1.6 0.4]
 [5.  3.6 1.4 0.2]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [6]:
# Step 4 : Then We Normalize the Data
from sklearn.preprocessing import StandardScaler

# Normalization is Done so That the Differcnce Between Highest and Lowest Data Point is not too Large
import numpy as np
scaler = StandardScaler()

# To Find Mean and Std Dev
scaler.fit(x_train)

# Converting Data into Form Where Mean of Data is 0 and and Std Dev is 1
X_train = scaler.transform(x_train)
X_test = scaler.transform(x_test)
print(np.amax(X_train, axis = 0))
print(np.amin(X_train, axis = 0))

[2.45148038 3.15321887 1.76869873 1.71577864]
[-1.92551986 -2.41431744 -1.61238307 -1.54279275]


In [7]:
# Step 5 : Now Finally We Build the Model Using Keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim = X_train.shape[1], activation = 'relu'))

# Dropout is Used to Avoid Overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation = 'relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation = 'relu'))
keras.layers.Dropout(0.2)
# For Classification Problems, We Usually Use Softmax as Activation Function is Final Layer
model.add(Dense(3, activation = 'softmax'))

# Compiling the Model
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [8]:
# Step 6 : Know the Model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1003 (3.92 KB)
Trainable params: 1003 (3.92 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
# Step 7 : Train the Model
# Batch Size, Epochs and Validation Split are All Hyper Parameters
model.fit(X_train, y_train, epochs = 195, batch_size = 80, validation_split = 0.1)

Epoch 1/195
2/2 [==============================] - 1s 156ms/step - loss: 1.1024 - accuracy: 0.1322 - val_loss: 1.0784 - val_accuracy: 0.4286
Epoch 2/195
2/2 [==============================] - 0s 21ms/step - loss: 1.0876 - accuracy: 0.2562 - val_loss: 1.0671 - val_accuracy: 0.5000
Epoch 3/195
2/2 [==============================] - 0s 22ms/step - loss: 1.0727 - accuracy: 0.4545 - val_loss: 1.0553 - val_accuracy: 0.5714
Epoch 4/195
2/2 [==============================] - 0s 22ms/step - loss: 1.0576 - accuracy: 0.5041 - val_loss: 1.0437 - val_accuracy: 0.5714
Epoch 5/195
2/2 [==============================] - 0s 23ms/step - loss: 1.0426 - accuracy: 0.5289 - val_loss: 1.0321 - val_accuracy: 0.7857
Epoch 6/195
2/2 [==============================] - 0s 23ms/step - loss: 1.0282 - accuracy: 0.5702 - val_loss: 1.0197 - val_accuracy: 0.7857
Epoch 7/195
2/2 [==============================] - 0s 21ms/step - loss: 1.0132 - accuracy: 0.6033 - val_loss: 1.0067 - val_accuracy: 0.7857
Epoch 8/195
2/2 [==

In [11]:
# Step 8 : Get the Accuracy of Model on Testing Data
testing = model.evaluate(X_test, y_test)
print("n%s: %.2f%%" % (model.metrics_names[1] + 'uracy of Model on testing data', testing[1]*100))

1/1 [==============================] - 0s 17ms/step - loss: 0.0040 - accuracy: 1.0000
naccuracyuracy of Model on Testing Data: 100.00%
1/1 [==============================] - 0s 30ms/step - loss: 0.0040 - accuracy: 1.0000
naccuracyuracy of Model on Testing Data: 100.00%


In [12]:
# Step 9 : Evaluate Our Model
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis = 1)
Y_test = np.argmax(y_test, axis = 1)

# To Get Confusion Matrix
print(confusion_matrix(Y_test, predictions))

# To Get Values of All Evaluation Metrics
print(classification_report(Y_test, predictions))

1/1 [==============================] - 0s 64ms/step
[[9 0 0]
 [0 2 0]
 [0 0 4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

